"""Initial migration with CommuteLogs

Revision ID: 6f9faf62219a
Revises: 
Create Date: 2026-04-29 23:41:31.361608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9faf62219a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_health_logs_endpoint'), 'api_health_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_health_logs_id'), 'api_health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_health_logs_timestamp'), 'api_health_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_line_user_id'), 'users', ['line_user_id'], unique=True)
    op.create_table('commute_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('target_arrival_time', sa.String(), nullable=True),
    sa.Column('suggested_departure_time', sa.String(), nullable=True),
    sa.Column('actual_departure_time', sa.String(), nullable=True),
    sa.Column('suggested_transport', sa.String(), nullable=True),
    sa.Column('actual_transport', sa.String(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('rain_prob', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('gmaps_traffic_duration', sa.Integer(), nullable=True),
    sa.Column('tdx_bus_eta', sa.Integer(), nullable=True),
    sa.Column('actual_arrival_time', sa.String(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commute_logs_date'), 'commute_logs', ['date'], unique=False)
    op.create_index(op.f('ix_commute_logs_id'), 'commute_logs', ['id'], unique=False)
    op.create_table('commute_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('home_city', sa.String(), nullable=True),
    sa.Column('office_address', sa.String(), nullable=True),
    sa.Column('office_lat', sa.Float(), nullable=True),
    sa.Column('office_lng', sa.Float(), nullable=True),
    sa.Column('office_city', sa.String(), nullable=True),
    sa.Column('preferred_arrival_time', sa.String(), nullable=True),
    sa.Column('walk_to_bus_stop_min', sa.Integer(), nullable=True),
    sa.Column('pending_field', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commute_profiles_id'), 'commute_profiles', ['id'], unique=False)
    op.create_table('commute_schedule_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commute_date', sa.Date(), nullable=False),
    sa.Column('target_arrival_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commute_schedule_overrides_commute_date'), 'commute_schedule_overrides', ['commute_date'], unique=False)
    op.create_index(op.f('ix_commute_schedule_overrides_id'), 'commute_schedule_overrides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commute_schedule_overrides_id'), table_name='commute_schedule_overrides')
    op.drop_index(op.f('ix_commute_schedule_overrides_commute_date'), table_name='commute_schedule_overrides')
    op.drop_table('commute_schedule_overrides')
    op.drop_index(op.f('ix_commute_profiles_id'), table_name='commute_profiles')
    op.drop_table('commute_profiles')
    op.drop_index(op.f('ix_commute_logs_id'), table_name='commute_logs')
    op.drop_index(op.f('ix_commute_logs_date'), table_name='commute_logs')
    op.drop_table('commute_logs')
    op.drop_index(op.f('ix_users_line_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_health_logs_timestamp'), table_name='api_health_logs')
    op.drop_index(op.f('ix_api_health_logs_id'), table_name='api_health_logs')
    op.drop_index(op.f('ix_api_health_logs_endpoint'), table_name='api_health_logs')
    op.drop_table('api_health_logs')
    # ### end Alembic commands ###
